## Wrangling Covid-19 Case Surveillance Dataframe

This notebook will load the current dataframe, which contains over 8,400,000 rows.  It will briefly examine the loaded

dataframe and then clean it up by doing the following:

- Making a copy of dataframe calling it df_wrangle
- Gives an overview of each column's values
- Replaces 'Missing' and 'Unknown' values with null values
- Iterates through each column and resets df_wrangle to filter out rows that have null values in that respective column
- row index is reset in df_wrangle
- Iterates through each column again and assigns the first three columns to datetime and the rest of the columns
    to categorical
- Renames 'Race and ethnicity (combined)' column to race_and_ethnicity
- Saves the cleaned dataframe as 'COVID-19_case_surveillance_wrangled.csv'

In [1]:
#importing pandas

import pandas as pd

In [2]:
#loading dataframe

df = pd.read_csv('COVID-19_Case_Surveillance_Public_Use_Data.csv')
df.head()

C:\Users\westi\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,cdc_report_dt,pos_spec_dt,onset_dt,current_status,sex,age_group,Race and ethnicity (combined),hosp_yn,icu_yn,death_yn,medcond_yn
0,2020/11/10,2020/11/10,NaN,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",No,Unknown,No,No
1,2020/11/14,2020/11/10,2020/11/10,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",No,No,No,No
2,2020/11/19,2020/11/10,2020/11/09,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",No,No,No,No
3,2020/11/14,2020/11/10,NaN,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",Missing,Missing,No,Missing
4,2020/11/13,2020/11/10,2020/11/10,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",No,No,No,Yes

In [3]:
#looking at size of dataframe

df.shape

(8405079, 11)

In [4]:
#examining datatypes

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8405079 entries, 0 to 8405078
Data columns (total 11 columns):
 #   Column                         Dtype
---  ------                         -----
 0   cdc_report_dt                  object
 1   pos_spec_dt                    object
 2   onset_dt                       object
 3   current_status                 object
 4   sex                            object
 5   age_group                      object
 6   Race and ethnicity (combined)  object
 7   hosp_yn                        object
 8   icu_yn                         object
 9   death_yn                       object
 10  medcond_yn                     object
dtypes: object(11)
memory usage: 705.4+ MB

## Brief Column Explanation:

- cdc_report_dt: Date CDC reported
    
- pos_spec_dt: Date of positive specimen collected
    
- onset_dt: The start date when person experienced Covid-19 symtoms
    
- current_status: Laboratory or confirmed case
    
- sex: sex of person
    
- age_group: demographic group of patient
    
- race and ethnicity (combined): race and ethnicity of patient
    
- hosp_yn: was patient hospitalized
    
- icu_yn: was patient in ICU
    
- death_yn: did patient die
    
- medcond_yn: did patient have underlying conditions

In [5]:
df.head()

,cdc_report_dt,pos_spec_dt,onset_dt,current_status,sex,age_group,Race and ethnicity (combined),hosp_yn,icu_yn,death_yn,medcond_yn
0,2020/11/10,2020/11/10,NaN,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",No,Unknown,No,No
1,2020/11/14,2020/11/10,2020/11/10,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",No,No,No,No
2,2020/11/19,2020/11/10,2020/11/09,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",No,No,No,No
3,2020/11/14,2020/11/10,NaN,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",Missing,Missing,No,Missing
4,2020/11/13,2020/11/10,2020/11/10,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",No,No,No,Yes

In [7]:
#value counts of columns
for column in df.columns:
    print(column,":")
    print(df[column].value_counts())
    print('\n')

cdc_report_dt :
2020/06/24    155857
2020/11/17    155142
2020/06/10    139250
2020/11/14    128908
2020/09/05    118092
               ...
2020/01/03         2
2020/01/28         1
2020/01/12         1
2020/01/08         1
2020/01/05         1
Name: cdc_report_dt, Length: 321, dtype: int64


pos_spec_dt :
2020/11/09    50595
2020/11/10    43495
2020/11/05    36216
2020/11/11    36210
2020/11/06    35417
              ...
2020/01/17        1
2020/01/21        1
2020/01/27        1
2020/02/06        1
2020/02/02        1
Name: pos_spec_dt, Length: 313, dtype: int64


onset_dt :
2020/11/02    49527
2020/11/03    46402
2020/11/04    46294
2020/11/06    41704
2020/10/26    41356
              ...
2020/01/16        7
2020/01/18        7
2020/01/08        6
2020/12/02        2
2020/12/03        2
Name: onset_dt, Length: 338, dtype: int64


current_status :
Laboratory-confirmed case    7910118
Probable Case                 494961
Name: current_status, dtype: int64


sex :
Female     4340898
Male       3970591
Unknown      73845
Missing      19520
Other          207
Name: sex, dtype: int64


age_group :
20 - 29 Years    1635264
30 - 39 Years    1372623
40 - 49 Years    1267350
50 - 59 Years    1227493
60 - 69 Years     863260
10 - 19 Years     841450
70 - 79 Years     483689
80+ Years         382869
0 - 9 Years       299040
Unknown            31952
Name: age_group, dtype: int64


Race and ethnicity (combined) :
Unknown                                                 2781176
White, Non-Hispanic                                     2599410
Hispanic/Latino                                         1195739
Black, Non-Hispanic                                      736584
Missing                                                  601519
Multiple/Other, Non-Hispanic                             270509
Asian, Non-Hispanic                                      143080
American Indian/Alaska Native, Non-Hispanic               59842
Native Hawaiian/Other Pacific Islander, Non-Hispanic      17213
Name: Race and ethnicity (combined), dtype: int64


hosp_yn :
No         3502556
Missing    3227302
Unknown    1136450
Yes         538771
Name: hosp_yn, dtype: int64


icu_yn :
Missing    6178281
Unknown    1286236
No          879671
Yes          60891
Name: icu_yn, dtype: int64


death_yn :
No         3690813
Missing    3486923
Unknown    1043766
Yes         183577
Name: death_yn, dtype: int64


medcond_yn :
Missing    6063390
Unknown     838018
Yes         785255
No          718416
Name: medcond_yn, dtype: int64

In [8]:
#making a copy of dataframe df_wrangle

df_wrangle = df.copy()

In [9]:
#replacing 'Missing' with 'Unknown'
df_wrangle = df_wrangle.replace('Missing', 'Unknown')

In [10]:
#replacing 'Unknown' with null values
df_wrangle = df_wrangle.replace('Unknown', np.nan)

In [12]:
#examping info with nulls
df_wrangle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8405079 entries, 0 to 8405078
Data columns (total 11 columns):
 #   Column                         Dtype
---  ------                         -----
 0   cdc_report_dt                  object
 1   pos_spec_dt                    object
 2   onset_dt                       object
 3   current_status                 object
 4   sex                            object
 5   age_group                      object
 6   Race and ethnicity (combined)  object
 7   hosp_yn                        object
 8   icu_yn                         object
 9   death_yn                       object
 10  medcond_yn                     object
dtypes: object(11)
memory usage: 705.4+ MB

In [14]:
#looping through each column to remove null values

for column in df_wrangle.columns:
    df_wrangle = df_wrangle[df_wrangle[column].notnull()]

In [15]:
#resetting index

df_wrangle = df_wrangle.reset_index(drop=True)

In [36]:
#info() method after nulls are removed

df_wrangle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294946 entries, 0 to 294945
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   cdc_report_dt       294946 non-null  datetime64[ns]
 1   pos_spec_dt         294946 non-null  datetime64[ns]
 2   onset_dt            294946 non-null  datetime64[ns]
 3   current_status      294946 non-null  category
 4   sex                 294946 non-null  category
 5   age_group           294946 non-null  category
 6   race_and_ethnicity  294946 non-null  category
 7   hosp_yn             294946 non-null  category
 8   icu_yn              294946 non-null  category
 9   death_yn            294946 non-null  category
 10  medcond_yn          294946 non-null  category
dtypes: category(8), datetime64[ns](3)
memory usage: 9.0 MB

In [32]:
#converting first three columns to datetime and rest to categorical

for count,column in enumerate(df_wrangle.columns):
    if count <=2:
        df_wrangle[column] = pd.to_datetime(df_wrangle[column])
    else:
        df_wrangle[column] = df_wrangle[column].astype('category')

In [35]:
#renaming Race and ethnicity (combined) column to race_and_ethnicity

df_wrangle.rename(columns={'Race and ethnicity (combined)':'race_and_ethnicity'}, inplace=True)

In [ ]:
#saving wrangled file

df_wrangle.to_csv('COVID-19_case_surveillance_wrangled.csv', index=False)